### ISSUE TITLE
Inkonsistente Nutzung von Markdown

### ISSUE THREAD

**Issue by pintman** [Firtz-Designs/firtz3.0#1]
Bei der summary einzelner Episoden wird Markdown nicht unterstützt, bei den Shownotes dagegen schon. Mir ist dies bei der Verwendung von Gender-Sternchen aufgefallen, die in den Shownotes maskiert werden müssen, in der Beschreibung dagegen nicht. 

Wäre es möglich, Markdown auch in den Beschreibung zu nutzen? Oder den ersten Absatz der Shownotes direkt in die Beschreibung zu übernehmen?!

**Comment by McCouman** [comment]
Hi @pintman,
letzteres wäre eine Eigenart die für viele scher zu verstehen ist. Die Beschreibung "summary" ist im feed als xml Tag hinterlegt und darf kein HTML besitzen. Daher ist es auch nicht per Markdown nutzbar. Warum Du es dann absichtlich in der Beschreibung maskieren willst, ist mir etwas unklar? 

Dennoch ginge ein Zwischenmix und daher habe ich mal die XML angepasst. Du solltest nun in der Summary Markdown verwenden können. Beachte auch die max. mögliche Zeichenanzahl von 4000 Zeichen.

Ebenfalls habe ich die stribs heraus genommen. So können nun auch Enter verwendet werden.

Grüße M.C.
